In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from imblearn.over_sampling import ADASYN
%matplotlib inline
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import KFold, cross_val_score

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [0]:
data=pd.read_csv('NORMALIZADO.csv')

In [0]:
cols=['Age','BysunessTrave','DailyRate','Department','DistanceFromHome', 'Education', 'EducationField','EmployeeNumber','EnvironmentSatifaction', 'Gender', 'HourlyRate', 'Joblnvolvement', 'JobLevel'
      'JobRole','JobSatisfaction','MaritalStatus','MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel'
      'TotalWorkingYears', 'TraininTimesLastYear', 'WorkLifeBalance','YearAtCompany', 'YearInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager','Attrition']

In [0]:
data.colums=cols

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.


In [0]:
print(data.head(5))

   Age  BusinessTravel  ...  YearsWithCurrManager  Attrition
0   41               2  ...                     5          1
1   53               2  ...                     7          0
2   36               2  ...                     3          1
3   42               2  ...                     2          0
4   46               2  ...                     1          0

[5 rows x 32 columns]


In [0]:
print(data.shape)

(446, 32)


In [0]:
print(data['Attrition'].value_counts())

0    354
1     92
Name: Attrition, dtype: int64


In [0]:
from collections import Counter

In [0]:
Datos=data.iloc[:,:-1].values#todas menos la ultima
Categoria=data.iloc[:,-1].values #ultima columna

In [0]:
print('Shape of Feature Matrix:',Datos.shape)
print('Shape of target vector:',Categoria.shape)

Shape of Feature Matrix: (446, 31)
Shape of target vector: (446,)


In [0]:
print('Original target variable distribution:', Counter(Categoria))


Original target variable distribution: Counter({0: 354, 1: 92})


In [0]:
ada= ADASYN(sampling_strategy='minority', random_state=4,n_neighbors=1)

In [0]:
DatosNorma, CategoriaNorma =ada.fit_resample(Datos,Categoria)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [0]:
print('OVersampled Target variable distribucion;', Counter(CategoriaNorma))

OVersampled Target variable distribucion; Counter({1: 380, 0: 354})


In [0]:
############################################# modelos SVM ##############################################################

In [0]:
print(DatosNorma)

[[  41    2 1102 ...    4    0    5]
 [  53    2 1219 ...    8    3    7]
 [  36    2 1218 ...    3    0    3]
 ...
 [  47    1 1122 ...    5    0    4]
 [  46    1 1231 ...    6    0    6]
 [  46    1 1181 ...    6    0    5]]


In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(DatosNorma,CategoriaNorma,test_size=0.3,random_state=109)


In [0]:
from sklearn import svm

In [0]:
clf = svm.SVC(kernel='linear')

In [0]:
clf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = clf.predict(X_test)

In [0]:
from sklearn import metrics

In [0]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8009049773755657


In [0]:
from sklearn.metrics import classification_report, confusion_matrix

In [0]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 72  22]
 [ 22 105]]
              precision    recall  f1-score   support

           0       0.77      0.77      0.77        94
           1       0.83      0.83      0.83       127

    accuracy                           0.80       221
   macro avg       0.80      0.80      0.80       221
weighted avg       0.80      0.80      0.80       221



#####################################DIFERENTE KERNEL

In [0]:
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svclassifier.predict(X_test)

In [0]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 85   9]
 [103  24]]
              precision    recall  f1-score   support

           0       0.45      0.90      0.60        94
           1       0.73      0.19      0.30       127

    accuracy                           0.49       221
   macro avg       0.59      0.55      0.45       221
weighted avg       0.61      0.49      0.43       221



In [0]:
###################################################### KERNEL: GAUSSIANO##################################################

In [0]:
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svclassifier.predict(X_test)

In [0]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.5067873303167421


In [0]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[59 35]
 [74 53]]
              precision    recall  f1-score   support

           0       0.44      0.63      0.52        94
           1       0.60      0.42      0.49       127

    accuracy                           0.51       221
   macro avg       0.52      0.52      0.51       221
weighted avg       0.53      0.51      0.50       221



#############KERNEL SIGMOIDE##################################################

In [0]:
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svclassifier.predict(X_test)

In [0]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[49 45]
 [62 65]]
              precision    recall  f1-score   support

           0       0.44      0.52      0.48        94
           1       0.59      0.51      0.55       127

    accuracy                           0.52       221
   macro avg       0.52      0.52      0.51       221
weighted avg       0.53      0.52      0.52       221

