In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split

In [0]:
Data=pd.read_csv('NORMALIZADO.csv')

In [0]:
Data.shape

(446, 32)

In [0]:
Data.head

<bound method NDFrame.head of      Age  BusinessTravel  ...  YearsWithCurrManager  Attrition
0     41               2  ...                     5          1
1     53               2  ...                     7          0
2     36               2  ...                     3          1
3     42               2  ...                     2          0
4     46               2  ...                     1          0
..   ...             ...  ...                   ...        ...
441   45               2  ...                     1          0
442   50               2  ...                     0          1
443   39               2  ...                     6          0
444   26               2  ...                     0          0
445   49               1  ...                     8          0

[446 rows x 32 columns]>

In [0]:
X = Data.drop('Attrition', axis=1)
y = Data['Attrition']

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [0]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svclassifier.predict(X_test)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[68  5]
 [15  2]]
              precision    recall  f1-score   support

           0       0.82      0.93      0.87        73
           1       0.29      0.12      0.17        17

    accuracy                           0.78        90
   macro avg       0.55      0.52      0.52        90
weighted avg       0.72      0.78      0.74        90



In [0]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7777777777777778


KERNEL POLINOMIAL

In [0]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svclassifier.predict(X_test)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[73  0]
 [17  0]]
              precision    recall  f1-score   support

           0       0.81      1.00      0.90        73
           1       0.00      0.00      0.00        17

    accuracy                           0.81        90
   macro avg       0.41      0.50      0.45        90
weighted avg       0.66      0.81      0.73        90



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8111111111111111


In [0]:
KENEL SIGMOID

In [0]:
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svclassifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[65  8]
 [16  1]]
              precision    recall  f1-score   support

           0       0.80      0.89      0.84        73
           1       0.11      0.06      0.08        17

    accuracy                           0.73        90
   macro avg       0.46      0.47      0.46        90
weighted avg       0.67      0.73      0.70        90



In [0]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7333333333333333
